language: rust
sudo: false
matrix:
  include:
    - rust: stable
    - rust: nightly
script:
  - |
      cargo build --verbose --features "$FEATURES"
      cargo test --verbose --features "$FEATURES"
      [ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES"
      cargo doc --verbose --features "$FEATURES"
